### ISSUE TITLE
Use available font weights

### ISSUE THREAD

**Issue by curran** [unhcr/dataviz-styleguide#19]
@vidonne The file `chart-typography.svg` contains recommendations for font weights, however those listed are not available for the Lato font. I suggest updating this according to the following mapping, from [Google Fonts](https://fonts.google.com/specimen/Lato?selection.family=Lato:300,400,700,900):

![image](https://user-images.githubusercontent.com/68416/29409759-5c09405a-836b-11e7-992c-58ca5a3d9a0f.png)
Lato

thin 100
thin 100 Italic
light 300
light 300 Italic
regular 400
regular 400 Italic
bold 700
bold 700 Italic
black 900
black 900 Italic

**Comment by vidonne** [comment]
@curran Thanks I used the Lato website as a reference and didn't notice google didn't have the whole set I'll update the settings
