### ISSUE TITLE
Add gh-pages for the repo

### ISSUE THREAD

**Issue by Edouard-Legoupil** [unhcr/dataviz-styleguide#22]
Create a github page to display an HTML version of the styleguide

**Comment by curran** [comment]
Yes this is a great idea! Perhaps the best way would be to configure GitHub Pages to use the master branch. I believe @matthewsmawfield is the only one who can change that setting (I don't have permissions, I don't see the "settings" tab).

**Comment by curran** [comment]
@matthewsmawfield Do you agree this would be a good change to make?

![image](https://user-images.githubusercontent.com/68416/29552976-1aefadbe-8737-11e7-93f4-73c66cea855f.png)

**Comment by curran** [comment]
This has been done, the page is published at https://unhcr.github.io/dataviz-styleguide/index.html

**Comment by matthewsmawfield** [comment]
i had missed this, sorry.
