### ISSUE TITLE
Create a ggplot2 implementation of UNHCR style guide

### ISSUE THREAD

**Issue by Edouard-Legoupil** [unhcr/dataviz-styleguide#23]
suggest to develop a “UNHCR style” for R (font, colors, layout, etc..) 

From ggplot2, all type of charts can be exported as SVG that can be then imported as vector object in Illustrator/Indesign for publication. [Theme](http://ggplot2.tidyverse.org/reference/theme.html) is one of the great feature of ggplot2.  Through the [ggtheme package](https://cran.r-project.org/web/packages/ggthemes/vignettes/ggthemes.html), it’s already easy to have styling based on “The economist”, “Excel”, “Fivethirtyeight”, “Stata”, “Tufte”, “The Wall street Journal”, “Google doc” or “High Chart”… 

We could definitely add UNHCR on that list! This would be definitely useful for the automated data crunching of household survey performed with [koboloader](https://github.com/Edouard-Legoupil/koboloadeR/blob/master/README.md)

**Comment by curran** [comment]
Wow, I did not know about ggtheme!

This would get us a huge number of UNHCR-themed visualization types at once. This might be the best place to start on templates, because once we do this, we'll have a basis for creating the other templates for many visualization types.

**Comment by curran** [comment]
@Edouard-Legoupil Have you worked with ggtheme? Would you be able to create a starting point for this? If those themes, like "Tufte" for example, are Open Source, maybe we can copy one of those and tweak it to our liking.

**Comment by curran** [comment]
Closing in favor of using Trello
