### ISSUE TITLE
Webify Data Colours

### ISSUE THREAD

**Issue by curran** [unhcr/dataviz-styleguide#25]
Implement these colors and this layout using Web technologies:
![image](https://user-images.githubusercontent.com/68416/29553013-398c895e-8737-11e7-938e-64d56f898eed.png)

**Comment by vidonne** [comment]
@curran do you really want to do as they will be part of the website too and not with the dame layout

**Comment by curran** [comment]
We want something like this in the Web version, right?

I can try to make it look the same as this. Or, I can make the layout different for Web.

Am I not understanding the direction correctly?

**Comment by vidonne** [comment]
[dataviz-styleguide-website.pdf](https://github.com/unhcr/dataviz-styleguide/files/1241458/dataviz-styleguide-website.pdf)
This is how it looks on the website for now still missing the colours code but it's the layout idea.

**Comment by curran** [comment]
Oh right! Sorry, I was looking at the wrong source document. Ok, I'll go off that design rather than the one I posted as a screenshot initially. Thanks for clarifying.

**Comment by curran** [comment]
Closing in favor of using Trello
