### ISSUE TITLE
Discuss Naming

### ISSUE THREAD

**Issue by curran** [unhcr/dataviz-styleguide#26]
@vidonne suggested "Graphics Styleguide", but I'm still rather keen on "Dataviz Styleguide". What do you all think? Do we really want to extend the scope to "all graphics", even non-data-visualizations?

**Comment by vidonne** [comment]
As agreed on slack let's call it "Data Visualisation Guideline". Let's see if it fits the banner

**Comment by curran** [comment]
I find it kind of funny that we're using British English (colour, visualisation) rather than American (color, visualization). Is that something standardized at UNHCR?

**Comment by vidonne** [comment]
It's what they used in the brandbook that's why with reused it

**Comment by curran** [comment]
Closing in favor of using Trello

**Comment by curran** [comment]
We're using British English so far.
