### ISSUE TITLE
Add Brand Colors to Customized Semantic UI

### ISSUE THREAD

**Issue by curran** [unhcr/dataviz-styleguide#30]
Here's a start at encoding the colors from our theme (using Less syntax):

```less
@blueLightest: #CCE3F2;
@blueLighter: #99C7E4;
@blueLight: #66AAD7;
@blue: #338EC9;
@blueDark: #0072BC;
@blueDarker: #00568D;
@blueDarkest: #18375F;
@redLightest: #FCDBDF;
@redLighter: #F9B7BF;
@redLight: #F592A0;
@red: #F26E80;
@redDark: #EF4A60;
@redDarker: #B33848;
@green: #00B398;
@yellow: #F5C300;
@white: #FFFFFF;
@grayLight: #ECECEC;
@gray: #AFAFAF;
@black: #000000;
@bluegrayLight: #E2E7EB;
@bluegray: #93A3AB;
@bluegrayDark: #72879D;
```
![image](https://user-images.githubusercontent.com/68416/29563350-c0a02162-875a-11e7-9525-6cd3857511c8.png)

**Comment by vidonne** [comment]
Nice!!!
There is actually something missing from the AI file is's the different tint and shades. Meaning that the one you actually called @blueDarkest is actually not based on UNHCR blue (@blueDark) but is the base color for a ramp of its own. Basically there are 6 main colours with tints and shades
<img width="459" alt="dataviz-styleguide-website_ai___66_67___rgb_gpu_preview_" src="https://user-images.githubusercontent.com/1830612/29563686-fcf54de8-873e-11e7-9900-e0c6d6c32496.png">

**Comment by vidonne** [comment]
For the name what about something like this https://material.io/guidelines/style/color.html#color-color-palette
For us it might be then @blue100, @blue200, @blue300, @blue400, @blue500, @blue600 where the 500 is the base color.

**Comment by curran** [comment]
I like that naming. That leaves open the possibility of subdividing the gradient further depending the number of colors/data values. Have you seen this tool https://vis4.net/labs/multihue/#colors=#CCE3F2,#99C7E4,#66AAD7,#338EC9,#0072BC,#00568D,#18375F|steps=9|bez=0|coL=1

**Comment by curran** [comment]
![image](https://user-images.githubusercontent.com/68416/29564231-936f0114-875e-11e7-81e6-9fa79930ea0f.png)
It interpolates colors. You can give as input the number of colors you want, and it will space them optimally for perception of difference.

**Comment by vidonne** [comment]
This is great!!!

**Comment by curran** [comment]
@vidonne Do we have the hex values somewhere for all of those "Shades of main colors"?

**Comment by vidonne** [comment]
We do have them working on implementing them in the AI file so you'll have everything there.

**Comment by matthewsmawfield** [comment]
I also like the naming suggestion, its consistent with font-weight so I
will be more likely to remember.

**Comment by curran** [comment]
![image](https://user-images.githubusercontent.com/68416/29623981-9f78ecc6-8845-11e7-81ff-c072d4d26841.png)
https://bl.ocks.org/curran/e1dfcba5740c8a847fab03bfef166bea

**Comment by curran** [comment]
Closing in favor of using Trello
