### ISSUE TITLE
Document how to use

### ISSUE THREAD

**Issue by curran** [unhcr/dataviz-styleguide#35]
Easiest way is to include via UNPKG CDN:

`<link rel="stylesheet" href="https://unpkg.com/dataviz-styleguide/semantic/dist/semantic.min.css">`

**Comment by matthewsmawfield** [comment]
Should the index page be including CSS using the recommended unpkg links so people can fork easily?

**Comment by curran** [comment]
I think this is done?

Closing in favor of using Trello
