### ISSUE TITLE
Remove built CSS files from repository

### ISSUE THREAD

**Issue by curran** [unhcr/dataviz-styleguide#55]
Including the built semantic.css and semantic.min.css as we are doing currently will cause merge headaches for us and also will bloat the size of the repository.

I propose we add all the generated files to `.gitignore`, and add a prepublish step to our `package.json`, so that whenever we publish a new version to NPM, the built files get generated and included there, so they can then be pulled down from UNPKG.

**Comment by matthewsmawfield** [comment]
yes this makes sense. please lets go ahead with your suggestion

**Comment by curran** [comment]
Great. I'll try it now.
