### ISSUE TITLE
Toggle style

### ISSUE THREAD

**Issue by matthewsmawfield** [unhcr/dataviz-styleguide#79]
Current
![screen shot 2017-09-07 at 16 08 34](https://user-images.githubusercontent.com/3186357/30170438-0bfd711c-93e7-11e7-8749-f6fc3398f2d9.jpg)

Desired
![screen shot 2017-09-07 at 16 08 55](https://user-images.githubusercontent.com/3186357/30170439-0dd16a02-93e7-11e7-9db0-80df11095835.jpg)

**Comment by curran** [comment]
Closing in favor of using Trello
