### ISSUE TITLE
Re-create design from Illustrator

### ISSUE THREAD

**Issue by curran** [unhcr/dataviz-styleguide#9]
![image](https://user-images.githubusercontent.com/68416/29308507-bc5866ce-81c3-11e7-8d9f-e8ca12c5bb98.png)

**Comment by vidonne** [comment]
@curran what do you mean with this one illustrator creation or conversion to HTML/CSS from illustrator?

**Comment by curran** [comment]
I mean that this issue represents the task of conversion of that exact design in the image into HTML/CSS.

What was that link you showed me where they already had HTML pages with this design? Maybe we can leverage some of their CSS work.

**Comment by vidonne** [comment]
It was the global unhcr.org website

**Comment by curran** [comment]
Closing in favor of using Trello
